name: Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          zip -r release.zip . -x "*.git*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          body: "Release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}